# Generated by Django 2.2.12 on 2020-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='legal',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
