# Generated by Django 2.2.12 on 2020-06-02 09:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_auto_20200601_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
