# Generated by Django 2.2.12 on 2020-09-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socialnet',
            new_name='Link',
        ),
    ]
